[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Node.js version for the build
  NODE_VERSION = "18"
  # Enable Next.js runtime
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect rules for Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
