[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  # Node.js version for the build
  NODE_VERSION = "18"
  # Enable Next.js runtime
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  # Fallback environment variables for build
  NEXT_PUBLIC_SUPABASE_URL = "https://bboorbycdttevtavjhzm.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJib29yYnljZHR0ZXZ0YXZqaHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODQ2NDIsImV4cCI6MjA3Mzk2MDY0Mn0.M0crGtBpMeUPlvzN_KUvrtv1OjEB__H2o95xgYDV5CA"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect rules for Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
