#!/bin/bash

echo "🚀 Netlify Environment Variables Setup Guide"
echo "==========================================="
echo ""
echo "To fix the Netlify build error, you need to add these environment variables:"
echo ""
echo "1. Go to your Netlify dashboard: https://app.netlify.com"
echo "2. Select your site (notebook)"
echo "3. Go to Site settings → Environment variables"
echo "4. Add these two variables:"
echo ""
echo "Variable 1:"
echo "Key: NEXT_PUBLIC_SUPABASE_URL"
echo "Value: https://bboorbycdttevtavjhzm.supabase.co"
echo ""
echo "Variable 2:"
echo "Key: NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJib29yYnljZHR0ZXZ0YXZqaHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODQ2NDIsImV4cCI6MjA3Mzk2MDY0Mn0.M0crGtBpMeUPlvzN_KUvrtv1OjEB__H2o95xgYDV5CA"
echo ""
echo "5. Save the variables"
echo "6. Trigger a new deploy by going to Deploys → Trigger deploy → Deploy site"
echo ""
echo "✅ After adding these variables, your build should succeed!"
echo ""
echo "📝 Note: You can also set these via Netlify CLI:"
echo "netlify env:set NEXT_PUBLIC_SUPABASE_URL https://bboorbycdttevtavjhzm.supabase.co"
echo "netlify env:set NEXT_PUBLIC_SUPABASE_ANON_KEY eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJib29yYnljZHR0ZXZ0YXZqaHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODQ2NDIsImV4cCI6MjA3Mzk2MDY0Mn0.M0crGtBpMeUPlvzN_KUvrtv1OjEB__H2o95xgYDV5CA"
